name: Code Review Test

on:
  push

jobs:
  test-code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v2
        with: 
          message: | 
            **Hello Main**

